package chrislo27.rhre

import chrislo27.rhre.registry.Game
import chrislo27.rhre.registry.GameRegistry
import chrislo27.rhre.version.VersionChecker
import chrislo27.rhre.version.VersionState
import com.badlogic.gdx.Gdx
import com.badlogic.gdx.Input
import com.badlogic.gdx.graphics.GL20
import com.badlogic.gdx.graphics.Texture
import com.badlogic.gdx.utils.Align
import com.badlogic.gdx.utils.Array
import ionium.registry.AssetRegistry
import ionium.registry.ScreenRegistry
import ionium.screen.Updateable
import ionium.util.DebugSetting
import ionium.util.MathHelper
import ionium.util.Utils
import ionium.util.i18n.Localization
import ionium.util.render.TexturedQuad

class InfoScreen(m: Main) : Updateable<Main>(m) {

	private val RHCRDJ: String = "https://www.reddit.com/r/rhythmheaven/comments/5h5wu0/rhythm_heaven_custom_remix_dj_v12_is_out_now_26/"

	private val patternCount: Int by lazy {
		GameRegistry.instance().gameList.flatMap(Game::patterns).filter { !it.autoGenerated }.count()
	}

	private val soundCueCount: Int by lazy {
		GameRegistry.instance().gameList.map { it.soundCues.size }.sum()
	}

	override fun render(delta: Float) {
		Gdx.gl.glClearColor(0f, 0f, 0f, 1f)
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT)

		main.batch.begin()

		if (DebugSetting.debug) {
			val tex: Texture = AssetRegistry.getTexture("ptr_whole")
			val originX = main.camera.viewportWidth * 0.5f - tex.width * 0.5f
			val originY = 128f
			val adjust = (MathHelper.getTriangleWave(0.75f) - 0.5f) / 0.5f
			// hat
			// 59, 421, 186, 133
			TexturedQuad.renderQuad(main.batch, tex,
									originX + 59, originY + 288,
									originX + 59 + 186, originY + 288,
									originX + 59 + 186 + adjust * 16, originY + 288 + 133,
									originX + 59 + adjust * 16, originY + 288 + 133,
									(59f) / tex.width, (5f) / tex.height,
									(59f + 186f) / tex.width, (133f) / tex.height)
			TexturedQuad.renderQuad(main.batch, tex,
									originX, originY,
									originX + tex.width, originY,
									originX + tex.width, originY + tex.height - 133,
									originX, originY + tex.height - 133,
									0f, (5f + 133f) / tex.height,
									1f, 1f)
		}

		main.font.setColor(0.5f, 0.65f, 1f, 1f)
		main.font.draw(main.batch, "https://github.com/chrislo27/RhythmHeavenRemixEditor2", main.camera.viewportWidth * 0.5f,
					   main.camera.viewportHeight - main.font.capHeight, 0f, Align.center, false)
		main.font.draw(main.batch, "_________________________________________________________", main.camera.viewportWidth * 0.5f,
					   main.camera.viewportHeight - main.font.capHeight, 0f, Align.center, false)

		main.font.setColor(1f, 1f, 1f, 1f)

		main.font.data.setScale(0.75f)

		var height: Float = Utils.getHeightWithWrapping(main.font, Localization.get("info.credits"),
														main.camera.viewportWidth * 0.45f)

		main.font.draw(main.batch, Localization.get("info.credits"),
					   main.camera.viewportWidth * 0.025f,
					   main.camera.viewportHeight * 0.5f + height * 0.6f, main.camera.viewportWidth * 0.45f, Align.topLeft, true)
		main.font.data.setScale(1f)

		val stats: String = Localization.get("info.stats", "${GameRegistry.instance().gameList.size}", "$patternCount",
											 "$soundCueCount")
		height = Utils.getHeightWithWrapping(main.font, stats,
											 main.camera.viewportWidth * 0.45f)

		main.font.draw(main.batch, stats,
					   main.camera.viewportWidth * 0.525f,
					   main.camera.viewportHeight * 0.75f + height * 0.5f, main.camera.viewportWidth * 0.45f, Align.center, true)

		height = Utils.getHeightWithWrapping(main.font, Localization.get("info.rhcrdj"),
									main.camera.viewportWidth * 0.45f)

		main.font.draw(main.batch, Localization.get("info.rhcrdj"),
					   main.camera.viewportWidth * 0.525f,
					   main.camera.viewportHeight * 0.25f + height * 0.5f, main.camera.viewportWidth * 0.45f, Align.right, true)
		if (Utils.isButtonJustPressed(Input.Buttons.LEFT)) {
			if (main.getInputX() >= main.camera.viewportWidth * 0.525f &&
					main.camera.viewportHeight - main.getInputY() >= main.camera.viewportHeight * 0.25f - height * 0.5f - main.font.capHeight &&
					main.camera.viewportHeight - main.getInputY() <= main.camera.viewportHeight * 0.25f + height * 0.5f) {
				Gdx.net.openURI(RHCRDJ)
			} else if (main.getInputY() <= main.font.lineHeight * 1.25f * main.camera.zoom) {
				Gdx.net.openURI("https://github.com/chrislo27/RhythmHeavenRemixEditor2")
			}
		}

		if (VersionChecker.versionState != VersionState.GETTING
				&& VersionChecker.versionState != VersionState.FAILED) {
			main.font.draw(main.batch, Localization.get("info.version"),
						   main.camera.viewportWidth * 0.025f,
						   main.font.capHeight * 2 + main.font.lineHeight, main.camera.viewportWidth * 0.95f, Align.center,
						   true)
		}
		main.font.draw(main.batch, Localization.get("info.back"),
					   main.camera.viewportWidth * 0.025f,
					   main.font.capHeight * 2, main.camera.viewportWidth * 0.95f, Align.center, true)

		main.batch.end()
	}

	override fun renderUpdate() {
		if (Gdx.input.isKeyJustPressed(Input.Keys.ESCAPE)) {
			main.screen = ScreenRegistry.get("editor")
		} else if (Gdx.input.isKeyJustPressed(Input.Keys.V)) {
			if (Gdx.input.isKeyPressed(Input.Keys.CONTROL_LEFT) || Gdx.input.isKeyPressed(Input.Keys.CONTROL_RIGHT)) {

			} else if (VersionChecker.versionState != VersionState.GETTING
					&& VersionChecker.versionState != VersionState.FAILED) {
				main.screen = ScreenRegistry.get("version")
			}
		}
	}

	override fun tickUpdate() {
	}

	override fun getDebugStrings(array: Array<String>?) {
	}

	override fun resize(width: Int, height: Int) {
	}

	override fun show() {
	}

	override fun hide() {
	}

	override fun pause() {
	}

	override fun resume() {
	}

	override fun dispose() {
	}


}
