package chrislo27.rhre.registry

import chrislo27.rhre.inspections.InspectionFunction

data class Pattern(val id: String, val name: String, val isStretchable: Boolean = false, val cues: List<PatternCue>,
				   val autoGenerated: Boolean = false, val deprecated: List<String> = mutableListOf()) {

	var inspectionFunctions: List<InspectionFunction> = listOf()

	data class PatternCue(val id: String, val beat: Float, val track: Int, val duration: Float, val semitone: Int)

}
