package chrislo27.rhre.registry

data class Pattern(val id: String, val name: String, val isStretchable: Boolean = false, val cues: List<PatternCue>, val autoGenerated: Boolean = false) {

	data class PatternCue(val id: String, val beat: Float, val track: Int, val duration: Float, val semitone: Int) {

	}

}
