-- Dump certain games' cues and patterns
-- Used for deprecation testing

remix:removeAllCues()

local games = {"blueBirds", "donkDonk", "fanClub", "marchingOrders", "munchyMonk", "spaceDance"}

for _, g in pairs(games) do
	local game = registry.games[g]

	for cueId, cue in pairs(game.cues) do
		remix:addCue(cue.id, 0, 1, 1)
	end
	for patId, pat in pairs(game.patterns) do
		if not pat.autoGenerated then
			remix:addCue(pat.id, 0, 1, 1)
		end
	end
end
